version: '2'

services:


  mongodb:
    image: mongo:latest
    container_name: mongodb_container1
    hostname: localhost
    ports:
      - 27017:27017



  soulmate:
    build: soulmaterestservice/
    container_name: soulmateee1
    hostname: localhost
    ports:
      - 8030:8030
    depends_on:
      - mongodb
    restart: always




